translate introducing-the-new-jsx-transform
reactjs/pt-BR.reactjs.org pull request #462
Opened 2020-10-21 10:56 UTC by jhonmike

2020-11-09 01:51 UTC, jhonmike commented
Review Please @reactjs/reactjs-org-portuguese-brazil-translation

2020-11-10 20:10 UTC, cezaraugusto requested changes

2020-11-10 20:10 UTC, cezaraugusto commented on content/blog/2020-09-22-introducing-the-new-jsx-transform.md
> +A partir do Babel 8, `"automático"` será o tempo de execução padrão para ambos os plug-ins. Para obter mais informações, verifique a documentação do Babel para [@babel/plugin-transform-react-jsx](htt
`automatic` é um valor do campo `runtime`, não deve ser traduzido:

```js
{
  "plugins": [
    ["@babel/plugin-transform-react-jsx", {
      "runtime": "automatic"
    }]
  ]
}
```

2020-11-10 21:00 UTC, cezaraugusto approved these changes

2020-11-10 21:00 UTC, merged

2022-06-10 12:04 UTC, Santiles87 commented
Awesome !