tradução: add-react-to-a-website.md
reactjs/pt-br.reactjs.org pull request #626
Opened 2022-10-27 17:17 UTC by gustarpd

2023-01-24 20:47 UTC, jhonmike commented
@gustarpd consegue atualizar seu PR com a branch main, e tratar os conflitos, ae na sequência consigo aprovar

2023-03-01 00:31 UTC, tiagobarros01 requested changes

2023-03-01 00:31 UTC, tiagobarros01 commented on beta/src/pages/learn/add-react-to-a-website.md
> +Na página HTML, logo antes da tag de fechamento `</body>` tag, adicione três tags `<script>` para os seguintes arquivos:
```suggestion
Na página HTML, logo antes da tag de fechamento `</body>`, adicione três tags `<script>` para os seguintes arquivos:
```
A palavra "tag" depois de `</body>` não faz muito sentido aqui.

2023-03-01 00:31 UTC, tiagobarros01 commented on beta/src/pages/learn/add-react-to-a-website.md
> +- [**react-dom.development.js**](https://unpkg.com/react-dom@17/umd/react-dom.development.js) permite que o React renderize elementos HTML para o [DOM](https://developer.mozilla.org/docs/Web/API/Docu
```suggestion
- [**react-dom.development.js**](https://unpkg.com/react-dom@17/umd/react-dom.development.js) permite que o React renderize elementos HTML para a [DOM](https://developer.mozilla.org/docs/Web/API/Document_Object_Model).
```

2023-03-01 00:31 UTC, tiagobarros01 commented on beta/src/pages/learn/add-react-to-a-website.md
> +Verificação de saída [um exemplo que exibe o botão "Curtir" três vezes e passa alguns dados para ele](https://gist.github.com/rachelnabors/c0ea05cc33fbe75ad9bbf78e9044d7f8)!
```suggestion
Confira [um exemplo que exibe o botão "Curtir" três vezes e passa alguns dados para ele](https://gist.github.com/rachelnabors/c0ea05cc33fbe75ad9bbf78e9044d7f8)!
```

2023-03-01 00:31 UTC, tiagobarros01 commented on beta/src/pages/learn/add-react-to-a-website.md
> +### Etapa 5: otimize o JavaScript para produção
```suggestion
### Etapa 5: Otimize o JavaScript para produção 
```
Maiúscula 💅

2023-03-01 00:31 UTC, tiagobarros01 commented on beta/src/pages/learn/add-react-to-a-website.md
> +O JavaScript não Otimizado pode diminuir significativamente o tempo de carregamento da página para seus usuários. Antes de implantar seu site em produção, é uma boa ideia reduzir seus scripts.
```suggestion
O JavaScript não otimizado pode diminuir significativamente o tempo de carregamento da página para seus usuários. Antes de implantar seu site em produção, é uma boa ideia reduzir seus scripts.
```
Sem necessidade de ser maiúscula.

2023-03-01 00:31 UTC, tiagobarros01 commented on beta/src/pages/learn/add-react-to-a-website.md
> +No entanto, o React também oferece uma opção para usar   [JSX](/learn/writing-markup-with-jsx), uma sintaxe JavaScript semelhante a HTML
```suggestion
No entanto, o React também oferece uma opção para usar [JSX](/learn/writing-markup-with-jsx), uma sintaxe JavaScript semelhante a HTML
```
Remova esse espaço em branco.

2023-03-01 00:31 UTC, tiagobarros01 commented on beta/src/pages/learn/add-react-to-a-website.md
> +A maneira mais rápida de experimentar o JSX em seu projeto é adicionar o compilador Babel ao `<head>` da sua página junto com React e ReactDOM assim:
```suggestion
### Experimente o JSX

A maneira mais rápida de experimentar o JSX em seu projeto é adicionar o compilador Babel ao `<head>` da sua página junto com React e ReactDOM assim:
```
Deve ter uma linha entre os títulos e o conteúdo.

2023-03-01 00:31 UTC, tiagobarros01 commented on beta/src/pages/learn/add-react-to-a-website.md
> +Se você vir uma mensagem de erro dizendo "Você instalou por engano o pacote `babel`", você pode ter perdido [a etapa anterior](#add-jsx-to-a-project). Execute-o na mesma pasta e tente novamente.
```suggestion
Se você ver uma mensagem de erro dizendo "Você instalou por engano o pacote `babel`", você pode ter perdido [a etapa anterior](#add-jsx-to-a-project). Execute-o na mesma pasta e tente novamente.
```

2023-03-01 00:31 UTC, tiagobarros01 commented on beta/src/pages/learn/add-react-to-a-website.md
> +Como bônus, isso também permite que você use recursos de sintaxe JavaScript modernos, como classes, sem se preocupar em quebrar navegadores mais antigos. A ferramenta que acabamos de usar chama-se Ba
```suggestion
Como bônus, isso também permite que você use recursos de sintaxe JavaScript modernos, como classes, sem se preocupar em quebrar navegadores mais antigos. A ferramenta que acabamos de usar chama-se Babel, e você pode aprender mais sobre ele [na documentação](https://babeljs.io/docs/en/babel-cli/).
```

2023-03-01 00:31 UTC, tiagobarros01 commented on beta/src/pages/learn/add-react-to-a-website.md
> -You can place a "container" element like this `<div>` anywhere inside the `<body>` tag. React will replace any existing content inside HTML elements, so they are usually empty. You can have as many o
Porque você removeu essa parte do conteúdo?

2023-03-05 15:20 UTC, closed without merging